---
hadoop_yum_repository_url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.1.4.0
hadoop_yum_repository_gpgkey_url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.1.4.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
hadoop_yum_packages:
  - hadoop
  - hadoop-hdfs
  - hadoop-libhdfs
  - hadoop-yarn
  - hadoop-mapreduce
  - hadoop-client
  - openssl
  - java-1.8.0-openjdk-headless

hadoop_apt_repository: "deb http://public-repo-1.hortonworks.com/HDP/ubuntu18/3.x/updates/3.1.4.0 HDP main"
hadoop_apt_repository_key_id: "B9733A7A07513CAD"
hadoop_apt_packages:
  - hadoop
  - hadoop-hdfs
  - libhdfs0
  - hadoop-yarn
  - hadoop-mapreduce
  - hadoop-client
  - openssl
  - openjdk-8-jdk-headless

hadoop_hdfs_base_dir: /hadoop/hdfs
hadoop_hdfs_namenode_dir: "{{ hadoop_hdfs_base_dir }}/nn"
hadoop_hdfs_secondary_namenode_dir: "{{ hadoop_hdfs_base_dir }}/snn"
hadoop_hdfs_datanode_dir:
  - "{{ hadoop_hdfs_base_dir }}/dn"
hadoop_hdfs_datanode_address: "0.0.0.0:9866"
hadoop_hdfs_datanode_dns_interface: default
hadoop_hdfs_datanode_hostname: ''
hadoop_hdfs_client_use_datanode_hostname: false
hadoop_hdfs_datanode_use_datanode_hostname: false
hadoop_hdfs_log_dir: /var/log/hadoop/hdfs
hadoop_hdfs_pid_dir: /var/run/hadoop/hdfs

hadoop_yarn_nodemanager_hostname: '0.0.0.0'
hadoop_yarn_base_dir: /hadoop/yarn
hadoop_yarn_local_dir: "{{ hadoop_yarn_base_dir }}/local"
hadoop_yarn_local_log_dir: "{{ hadoop_hdfs_base_dir }}/logs"
hadoop_yarn_log_dir: /var/log/hadoop/yarn
hadoop_yarn_pid_dir: /var/run/hadoop/yarn

hadoop_mapred_log_dir: /var/log/hadoop/mapred
hadoop_mapred_pid_dir: /var/run/hadoop/mapred

hadoop_conf_dir: /etc/hadoop/conf

# FIXME
hadoop_hdp_version: 3.1.4.0

hadoop_hdfs_replication: 3

hadoop_yarn_scheduler_minimum_allocation_vcores: 1
hadoop_yarn_scheduler_maximum_allocation_vcores: 4

hadoop_yarn_scheduler_minimum_allocation_mb: 2048
hadoop_yarn_scheduler_maximum_allocation_mb: 26624
hadoop_yarn_nodemanager_resource_memory_mb: 26624
hadoop_yarn_nodemanager_vmem_check_enabled: false
hadoop_yarn_nodemanager_vmem_pmem_ratio: 2.1

hadoop_mapreduce_map_speculative: false
hadoop_mapreduce_reduce_speculative: false
hadoop_mapreduce_task_io_sort_factor: 100
hadoop_mapreduce_task_io_sort_mb: 1146
hadoop_mapreduce_map_memory_mb: 2048
hadoop_mapreduce_map_java_opts: -Xmx1638m
hadoop_mapreduce_reduce_memory_mb: 4096
hadoop_mapreduce_reduce_java_opts: -Xmx3276m
hadoop_yarn_app_mapreduce_am_resource_mb: 4096
hadoop_yarn_app_mapreduce_am_command_opts: -Xmx3276m

#
# S3A configuration
#
hadoop_fs_s3a_access_key: ''
hadoop_fs_s3a_secret_key: ''
hadoop_fs_s3a_endpoint: ''
hadoop_fs_s3a_path_style_access: true
hadoop_fs_s3a_fast_upload: true
hadoop_fs_s3a_block_size: '512M'
hadoop_fs_s3a_multipart_threshold: '512M'
hadoop_fs_s3a_multipart_size: '512M'
hadoop_fs_s3a_fast_upload_buffer: 'disk'
hadoop_fs_s3a_buffer_dir: '${hadoop.tmp.dir}/s3a/'
hadoop_fs_s3a_threads_max: 2048
hadoop_fs_s3a_fast_upload_active_blocks: 2048
hadoop_fs_s3a_connection_maximum: 8192
hadoop_fs_s3a_max_total_tasks: 2048
hadoop_fs_s3a_socket_recv_buffer: 65536
hadoop_fs_s3a_socket_send_buffer: 65536
hadoop_fs_s3a_committer_magic_enabled: false
hadoop_fs_s3a_committer_name: directory
hadoop_fs_s3a_committer_staging_abort_pending_uploads: true
hadoop_fs_s3a_committer_staging_conflict_mode: append
hadoop_fs_s3a_committer_staging_tmp_path: /tmp/staging/
hadoop_fs_s3a_committer_staging_unique_filenames: true
hadoop_fs_s3a_committer_threads: 2048


hadoop_core_site_custom: {}
hadoop_hdfs_site_custom: {}
hadoop_yarn_site_custom: {}
hadoop_mapred_site_custom: {}

hadoop_sysctl_entries:
  # max receive socket buffer (bytes)
  net.core.rmem_max: 268435456
  # max send socket buffer (bytes)
  net.core.wmem_max: 268435456
  # default receive socket buffer (bytes)
  net.core.rmem_default: 67108864
  # default send socket buffer (bytes)
  net.core.wmem_default: 67108864
  # max number of incoming connections
  net.core.somaxconn: 65535
  # reuse sockets in TIME_WAIT state
  net.ipv4.tcp_tw_reuse: 1
